### ISSUE TITLE
cmd-polkit does not release child processes

### ISSUE THREAD

**Issue by JU12000** [OmarCastro/cmd-polkit#4]
Thanks so much for the great tool, though I noticed something:

When running `exec cmd-polkit-agent -s -c "foo"` `foo` will eventually exit after processing a message. However, `cmd-polkit` does nothing with the `SIGCHLD` kill signal so each instance of `foo` spawned (due to the -s flag) will exit and become a zombie process. The only way to clear these is to periodically stop and restart `cmd-polkit-agent` which is not idea for long-running user sessions.

`cmd-polkit` should properly release child processes created by the `-c` flag.

**Comment by OmarCastro** [comment]
Hello @JU12000 , the idea is that an external long running process handles the login logic, 

As far as I remember, foo was supposed to receive in each line a command from cmd-polkit and handle it, be it by creating an external process and such, the objective of this project is to easily create handlers using stdin and stdout, you can use any language, so the ´foo´ program should handle the creation/management of the sub process

But then again, it should handle errors that happens when ´foo´ exits due to a failure

To solve this issue, I will mostly add documentation to explain this as to avoid any kind of misusage and create an handler to log the exit of the subprocess and create it

**Comment by OmarCastro** [comment]
I remembered wrong, the idea of doing a long process was my next step in the development, but was incomplete, I have the fix for this issue, gotta commit in a bit

**Comment by OmarCastro** [comment]
Tested and releasing correctly, I am going to close this issue as fixed, feel free to reopen if something is wrong
