### ISSUE TITLE
Performance Impact

### ISSUE THREAD

**Issue by mageowl** [OmarCastro/cmd-polkit#7]
While active, daemon is frequently using 10-20% of CPU.

**Comment by OmarCastro** [comment]
Hello @mageowl, there is little information to explain what is happening to help you.

What do you mean active? is it when you are writing the password? when cmd-polkit is running?

There is this issue #6 that is related to zombie children processes making a spike on the CPU and it is solved.

Also, if you can show the script used on `-c` command it would help reproduce the issue since it is not happening to me

**Comment by mageowl** [comment]
Sorry! While the process is running in the background (not actively open) it was using 10%-20% of CPU. Updating fixed the issue.
